// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "orders/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// Delete provides a mock function with given fields: orderUID
func (_m *Cache) Delete(orderUID string) {
	_m.Called(orderUID)
}

// Get provides a mock function with given fields: key
func (_m *Cache) Get(key string) (*models.OrderJSON, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.OrderJSON
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*models.OrderJSON, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *models.OrderJSON); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrderJSON)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Set provides a mock function with given fields: key, value
func (_m *Cache) Set(key string, value *models.OrderJSON) {
	_m.Called(key, value)
}

// WarmUpCache provides a mock function with given fields: orders
func (_m *Cache) WarmUpCache(orders []models.OrderJSON) error {
	ret := _m.Called(orders)

	if len(ret) == 0 {
		panic("no return value specified for WarmUpCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]models.OrderJSON) error); ok {
		r0 = rf(orders)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
