{
 "title": "Orders Service Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_messages_total,topic)"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(kafka_messages_total{\"$status\"=\"$topic\"},status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka Processing Attempts",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (attempts) (rate(kafka_processing_attempts_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders in Cache",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orders_in_cache", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kafka Messages",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_messages_total{status=\"success\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kafka_messages_total{status=\"error\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Orders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orders_created_total{status=\"error\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Orders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(orders_created_total{status=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka P95 Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(kafka_message_processing_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}